#
# Analyze repository with PSRule for Azure
#

# Note:
# This workflow is designed to run in templated repositories to check Azure Infrastructure as Code.

# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze Azure resources

# Run for main or PRs against main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # # Run analysis by using the PSRule GitHub action.
    # - name: Run PSRule analysis
    #   uses: microsoft/ps-rule@v2.6.0
    #   with:
    #     modules: 'PSRule.Rules.Azure'

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x

    # Run analyzers
    - name: Run Microsoft Security DevOps Analysis
      uses: microsoft/security-devops-action@v1.6
      id: msdo

    # Upload alerts to the Security tab
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
